### ISSUE TITLE
DataService

### ISSUE THREAD

**Issue by DoubleExposure** [DanWahlin/Angular2-CustomerManager#1]
Dan, I need a little help. I am trying to integrate this into a Webpack based application.
I see where you call the getCustomer() method for pulling data but I do not see where or how you point to the data folder to pull it. I also see the http call using the url. But the url says /api/customers/ 
How are you pulling the data from the DATA folder which is in your root folder? Can you help? I simply do not see it. Thanks

**Comment by DanWahlin** [comment]
This isn't a project I'd use since it uses an old version of Angular 2. The data is pulled from MongoDB though via a Node restful service.

I'd recommend my Angular 2 Jumpstart project.
